apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ilt3qt31n-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ilt3qt31n-java-quarkus-gitops